---
stages:
  train:
    cmd: python src/train.py
    deps:
      - data
      - src/train.py
    params:
      - process.batch_size
      - train.lr
      - train.epochs
    metrics:
      - metrics.json:
          cache: false
    plots:
      - loss.csv:
          cache: false
