stages:
  train:
    cmd: python src/train.py
    deps:
      - data
      - src/train.py
      - src/model.py
      - src/utils.py
      - src/data.py
      - src/config.py
      - src/custom_metrics.py
    params:
      - process.batch_size
      - train.lr
      - train.epochs
    metrics:
      - metrics.json:
          cache: false
    outs:
      - model/:
          cache: false
    plots:
      - loss.csv:
          cache: false
      - val_loss.csv:
          cache: false
      - matrix.csv:
          cache: false
          x: actual
          y: predicted
          template: confusion
