stages:
  train:
    cmd: python src/train.py
    deps:
      - data
      - src/train.py
    params:
      - process.batch_size
      - train.lr
      - train.epochs
    metrics:
      - metrics.json:
          cache: false
    outs:
      - model_weights.h5
    plots:
      - loss.csv:
          cache: false
      - val_loss.csv:
          cache: false
      - matrix.csv:
          cache: false
          x: actual
          y: predicted
          template: confusion
